# Generated by Django 6.0.5 on 2026-05-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sesiujian_test_sesi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='siswa',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='dosen',
        ),
    ]
