# Generated by Django 6.0.5 on 2026-05-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_siswa_test_user_remove_test_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sop',
            field=models.CharField(blank=True, null=True),
        ),
    ]
