# Generated by Django 6.0.5 on 2026-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_test_sop'),
    ]

    operations = [
        migrations.AddField(
            model_name='soalsop',
            name='bobot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
