# Generated by Django 6.0.5 on 2026-06-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_soalsop_bobot_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsoalsop',
            name='bobot',
            field=models.IntegerField(default=0),
        ),
    ]
