# Generated by Django 6.0.5 on 2026-06-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_detailsoalsop_bobot'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
            ],
        ),
    ]
